Repository tusharzalte/tusharesume, pull requests merged in 2023-06, with the labels that each got.

#93 📝 DOCS: ADD DYNAMICALLY GENERATED CONTRIBUTORS GRAPH
  README.md
Labels: documentation, enhancement, GSSOC'23, level0

#107 favicon added
  client1/public/favicon.png
  client1/public/index.html
Labels: GSSOC'23, level0

#100 #91 Greeting bot added
  .github/ISSUE_TEMPLATE/workflows/greetings.yml
Labels: GSSOC'23, level2

#101 Issue #97 Added the feature navigation after registration and fixed some bugs
  client1/src/Pages/Login.js
  client1/src/Pages/Register.js
  routes/userRoute.js
Labels: enhancement, GSSOC'23, level2

#103 Warnings, Errors and Orientation fixed.
  client1/src/Pages/Login.js
  client1/src/Resources/Stylesheets/authentication.css
  client1/src/Resources/Stylesheets/footer.css
  package-lock.json
  package.json
  server.js
Labels: enhancement, GSSOC'23, level1

#113 Fixed #111 - PR Template
  .github/pull_request_template.yml
Labels: enhancement, GSSOC'23, level2

#112 #90 Depandabot Added
  .github/dependabot.yml
Labels: enhancement, GSSOC'23, level1

#121 Update README.md
  README.md
Labels: documentation, GSSOC'23, level0

#128 #92 Bot Added
  .github/workflows/close_old_issues.yaml
  .github/workflows/greetings.yml
Labels: GSSOC'23, level1

#134 Meta tags added
  client1/public/index.html
Labels: GSSOC'23, level1

#147 Add JWT Middleware #25
  jwt.js
  package-lock.json
  package.json
  routes/userRoute.js
Labels: GSSOC'23, level1
