Repository tusharzalte/tusharesume, pull requests merged in 2023-05, with the labels that each got.

#73 Readme Updated
  README.md
Labels: documentation, enhancement, GSSOC'23

#75 Changed class to className
  client1/src/Components/Footer.js
Labels: bug, GSSOC'23, level1

#79 Update LICENSE
  LICENSE
Labels: documentation, GSSOC'23, level1

#76 Reset the register form
  client1/src/Pages/Register.js
Labels: enhancement, GSSOC'23, level2

#88 Added animations to different buttons
  client1/src/Resources/Stylesheets/authentication.css
  client1/src/Resources/Stylesheets/defaultlayout.css
  client1/src/Resources/Stylesheets/profile.css
  client1/src/index.css
Labels: enhancement, GSSOC'23, level1

#77 Added unique key to map function
  client1/src/Pages/Home.js
Labels: bug, level0
