Repository tusharzalte/tusharesume, pull requests merged in 2023-07, with the labels that each got.

#155 Add show/hide password feature
  client/package-lock.json
  client/package.json
  client/src/Pages/Login.js
  client/src/Pages/Register.js
  client/src/Resources/Stylesheets/authentication.css
Labels: bug, gssoc23

#182 Update README.md
  README.md
Labels: documentation, enhancement, level2, gssoc23

#183 Update README.md
  README.md
Labels: enhancement, level2, gssoc23

#185 Readme edit
  README.md
Labels: documentation, enhancement, level2, gssoc23
